name: time_capsule
description: A simple app to send messages to your future self.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Date/Time
  intl: ^0.18.1

  # Background Work
  flutter_local_notifications: ^16.2.0
  workmanager: ^0.5.1
  shared_preferences: ^2.2.2

  # Navigation
  go_router: ^12.1.1

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
